### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by iOSRoad** [gsdios/SDRefreshView#1]
（回复）你好，在下拉到一定距离而未触发刷新之前，松开即可自动弹回而不刷新，如果下拉距离达到了整个refreshView的高度就触发刷新，这时候已经发出网络请求等待回传数据，不能再取消，而是在数据加载完毕后才取消。请在你的加载数据的请求完成时调用refreshView的endRefreshing方法通知refreshView数据已经加载完成从而自动隐藏刷新控件（refreshView）。

（问题）下拉的时候，往上拉应该是取消刷新，而你这个往上拉还会刷新，希望改进

**Comment by iOSRoad** [comment]
下拉也是这样！

**Comment by gsdios** [comment]
你好，在下拉到一定距离而未触发刷新之前，松开即可自动弹回而不刷新，如果下拉距离达到了整个refreshView的高度就触发刷新，这时候已经发出网络请求等待回传数据，不能再取消，而是在数据加载完毕后才取消。请在你的加载数据的请求完成时调用refreshView的endRefreshing方法通知refreshView数据已经加载完成从而自动隐藏刷新控件（refreshView）。

**Comment by iOSRoad** [comment]
。。。
